resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.9"

resources:
- name: demo-project
  type: git
  webhook_token: 573C9076AFA74928AFDAB4FE9E20E6AF
  source:
    uri: https://github.com/Evaneos/demo-project.git
    branch: master
- name: intraneos-cluster
  type: kubernetes
  source:
    kubeconfig: ((kubeconfig))

jobs:
- name: deploy-on-success
  plan:
  - get: demo-project
    trigger: true
  - task: unit-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: php, tag: 7.2.1-alpine}
      inputs:
      - name: demo-project
      run:
        path: sh
        args:
        - -exc
        - |
          curl -L -o /usr/local/bin/composer https://getcomposer.org/composer.phar
          chmod +x /usr/local/bin/composer
          composer global require hirak/prestissimo
          cd ./demo-project
          composer install
          ./vendor/bin/phpunit test
  - put: intraneos-cluster
    params:
      kubectl: apply -f demo-project/infra
